#!/bin/sh
set -e

VERSION="${REACT_APP_VERSION:-${APP_IMAGE_TAG:-}}"
LOGO_URL="${REACT_APP_BRAND_LOGO_URL:-}"
PUBLIC_SITE_URL="${PUBLIC_APP_URL:-${APP_URL:-}}"
LEGAL_OPERATOR_NAME="${LEGAL_OPERATOR_NAME:-}"
LEGAL_CONTACT_EMAIL="${LEGAL_CONTACT_EMAIL:-}"
LEGAL_LAST_UPDATED="${LEGAL_LAST_UPDATED:-}"

cat > /app/public/runtime-config.js <<EOF
window.__RUNTIME_CONFIG__ = {
  VERSION: "${VERSION}",
  BRAND_LOGO_URL: "${LOGO_URL}",
  PUBLIC_SITE_URL: "${PUBLIC_SITE_URL}",
  LEGAL_OPERATOR_NAME: "${LEGAL_OPERATOR_NAME}",
  LEGAL_CONTACT_EMAIL: "${LEGAL_CONTACT_EMAIL}",
  LEGAL_LAST_UPDATED: "${LEGAL_LAST_UPDATED}"
};
EOF

exec npm start
